name: Go

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main

env:
  GITHUB_NAME: pacoxu
  GITHUB_EMAIL: roollingstone@gmail.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Repos Status
        uses: ./
        with:
          WITH_STARED: false
          TELEGRAM_TOKEN: ${{ secrets.TELE_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}

      - name: My GitHub Status
        uses: pacoxu/github-repos-stats@multi-clusters
      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'docs: update readme.md'
          git push

