name: Run for main(all CNCF China related projects)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"
  push:
    branches:
      - main

env:
  GITHUB_NAME: pacoxu-bot
  GITHUB_EMAIL: paco2023@163.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: My GitHub Status
        uses: pacoxu/github-repos-stats@main
      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'docs: update readme.md'
          git push

